from pathlib import Path
root=Path('/tmp/pwm/static')
common_css='''<style>
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#050711;color:#fff;font-family:Inter,system-ui,Arial,sans-serif}canvas{display:block}#hud{position:fixed;z-index:5;top:12px;left:12px;right:12px;display:flex;justify-content:space-between;gap:8px;pointer-events:none}.pill{background:rgba(5,8,20,.75);border:1px solid rgba(120,210,255,.3);backdrop-filter:blur(8px);padding:8px 12px;border-radius:12px;font-weight:800;text-shadow:0 2px 8px #000}.screen{position:fixed;inset:0;z-index:10;display:flex;align-items:center;justify-content:center;background:radial-gradient(circle at 50% 35%,rgba(30,60,110,.5),rgba(2,4,12,.96));padding:24px}.panel{width:min(520px,94vw);padding:30px;border:1px solid rgba(130,220,255,.35);border-radius:24px;background:rgba(7,12,28,.86);box-shadow:0 25px 80px #000;text-align:center}.panel h1{font-size:clamp(30px,8vw,54px);margin:0 0 8px;letter-spacing:2px}.panel p{color:#aebbd2;line-height:1.55}.btn{border:0;border-radius:14px;padding:14px 24px;margin:7px;background:linear-gradient(135deg,#18bfff,#625cff);color:white;font-size:16px;font-weight:900;box-shadow:0 10px 30px rgba(30,170,255,.25);cursor:pointer}.btn.alt{background:rgba(255,255,255,.1);box-shadow:none}.hidden{display:none!important}.controls{position:fixed;z-index:6;bottom:18px;left:0;right:0;display:flex;justify-content:center;gap:12px;pointer-events:none}.control{pointer-events:auto;width:64px;height:64px;border-radius:50%;border:1px solid rgba(255,255,255,.25);background:rgba(10,18,38,.72);color:#fff;font-size:24px;font-weight:900;touch-action:none}.wide{width:120px;border-radius:20px;font-size:15px}.bar{height:8px;background:#20283a;border-radius:8px;overflow:hidden;width:150px}.fill{height:100%;width:100%;background:linear-gradient(90deg,#42e8ff,#7b5cff)}
</style>'''

def wrap(title, body, js):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><title>{title}</title><script src="https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js"></script>{common_css}</head><body>{body}<script>{js}</script></body></html>'''

shooter_body='''<div id="hud"><div class="pill">🚀 CYBER VOID · <span id="score">0</span></div><div class="pill">❤️ <span id="hp">100</span> · 🌊 <span id="wave">1</span></div></div><div id="start" class="screen"><div class="panel"><h1>CYBER VOID</h1><p>3D orbital combat. Destroy hostile drones, dodge incoming fire and survive as long as possible.</p><button class="btn" id="play">START MISSION</button></div></div><div id="over" class="screen hidden"><div class="panel"><h1>MISSION ENDED</h1><p>Final score: <b id="final">0</b></p><button class="btn" id="again">REDEPLOY</button><button class="btn alt" onclick="history.back()">BACK</button></div></div><div class="controls"><button class="control" id="left">◀</button><button class="control" id="fire">⚡</button><button class="control" id="right">▶</button></div>'''
shooter_js='''const tg=window.Telegram?.WebApp; tg?.ready();tg?.expand();let scene,camera,renderer,ship,enemies=[],shots=[],enemyShots=[],score=0,hp=100,wave=1,running=false,last=performance.now(),sessionId=null;const keys={};
function init(){scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x030611,.018);camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,1000);camera.position.set(0,5,14);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.appendChild(renderer.domElement);scene.add(new THREE.AmbientLight(0x6b88aa,1.5));let dl=new THREE.DirectionalLight(0xffffff,2.2);dl.position.set(5,12,8);scene.add(dl);let g=new THREE.GridHelper(220,55,0x155a88,0x092039);g.position.y=-3;scene.add(g);for(let i=0;i<180;i++){let m=new THREE.Mesh(new THREE.SphereGeometry(.035+Math.random()*.08,6,6),new THREE.MeshBasicMaterial({color:0x88ccff}));m.position.set((Math.random()-.5)*180,(Math.random()-.5)*100,(Math.random()-.5)*180);scene.add(m)};ship=makeShip();scene.add(ship);addEventListener('resize',resize);requestAnimationFrame(loop)}
function makeShip(){let g=new THREE.Group();let mat=new THREE.MeshStandardMaterial({color:0x1fc7ff,metalness:.75,roughness:.2});let dark=new THREE.MeshStandardMaterial({color:0x18253c,metalness:.7});let body=new THREE.Mesh(new THREE.ConeGeometry(1,3.5,4),mat);body.rotation.x=Math.PI/2;g.add(body);let wing=new THREE.Mesh(new THREE.BoxGeometry(3,.18,1.2),dark);g.add(wing);let glow=new THREE.PointLight(0x22ddff,4,8);glow.position.z=1.4;g.add(glow);g.position.y=-1.3;return g}
function makeEnemy(){let g=new THREE.Group();let mat=new THREE.MeshStandardMaterial({color:0xff315d,metalness:.6,roughness:.25});let core=new THREE.Mesh(new THREE.IcosahedronGeometry(.9,1),mat);g.add(core);let ring=new THREE.Mesh(new THREE.TorusGeometry(1.25,.08,8,24),new THREE.MeshBasicMaterial({color:0xff6b8c}));ring.rotation.x=Math.PI/2;g.add(ring);g.position.set((Math.random()-.5)*15,Math.random()*6-1,-35-Math.random()*25);g.userData={hp:2,cool:Math.random()*2};scene.add(g);enemies.push(g)}
function fire(){if(!running)return;let s=new THREE.Mesh(new THREE.CylinderGeometry(.06,.06,1.8,8),new THREE.MeshBasicMaterial({color:0x56e8ff}));s.rotation.x=Math.PI/2;s.position.copy(ship.position);s.position.z-=2;scene.add(s);shots.push(s)}
async function startSession(){try{let r=await fetch('/api/game/start',{method:'POST',headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||''},body:JSON.stringify({game:'shooter'})});let d=await r.json();if(d.status==='success')sessionId=d.session_id}catch(e){console.warn(e)}}
async function finish(){running=false;document.getElementById('final').textContent=score;document.getElementById('over').classList.remove('hidden');if(sessionId){try{await fetch('/api/save-score',{method:'POST',headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||''},body:JSON.stringify({game:'shooter',score,session_id:sessionId})})}catch(e){}}}
function start(){score=0;hp=100;wave=1;document.getElementById('score').textContent=0;document.getElementById('hp').textContent=100;document.getElementById('wave').textContent=1;document.getElementById('start').classList.add('hidden');document.getElementById('over').classList.add('hidden');enemies.forEach(x=>scene.remove(x));shots.forEach(x=>scene.remove(x));enemyShots.forEach(x=>scene.remove(x));enemies=[];shots=[];enemyShots=[];running=true;startSession();for(let i=0;i<5;i++)makeEnemy()}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
function loop(t){let dt=Math.min(.035,(t-last)/1000);last=t;if(running){let dir=(keys.left?-1:0)+(keys.right?1:0);ship.position.x+=dir*9*dt;ship.position.x=Math.max(-7,Math.min(7,ship.position.x));ship.rotation.z=-dir*.22;if(Math.random()<dt*.9)fire();if(enemies.length<Math.min(5+wave,12)&&Math.random()<dt*.7)makeEnemy();enemies.forEach((e,ei)=>{e.position.z+=dt*(5+wave*.6);e.rotation.y+=dt*1.8;e.userData.cool-=dt;if(e.userData.cool<0){e.userData.cool=1.2+Math.random()*1.5;let b=new THREE.Mesh(new THREE.SphereGeometry(.14,8,8),new THREE.MeshBasicMaterial({color:0xff456d}));b.position.copy(e.position);scene.add(b);enemyShots.push(b)}if(e.position.z>10){hp-=10;e.position.z=-45;}});shots.forEach((s,si)=>{s.position.z-=dt*32;for(let ei=enemies.length-1;ei>=0;ei--){let e=enemies[ei];if(s.position.distanceTo(e.position)<1.2){e.userData.hp--;scene.remove(s);shots.splice(si,1);if(e.userData.hp<=0){score+=100;document.getElementById('score').textContent=score;scene.remove(e);enemies.splice(ei,1)}break}}});enemyShots.forEach((b,bi)=>{b.position.z+=dt*16;if(b.position.distanceTo(ship.position)<1.3){hp-=8;scene.remove(b);enemyShots.splice(bi,1)}});if(score>0&&score%500===0)wave=1+Math.floor(score/500);document.getElementById('hp').textContent=Math.max(0,hp);document.getElementById('wave').textContent=wave;if(hp<=0)finish()}camera.position.x+=(ship.position.x*.28-camera.position.x)*dt*5;camera.lookAt(ship.position.x*.25,0,-12)}renderer.render(scene,camera);requestAnimationFrame(loop)}
addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.left=true;if(e.key==='ArrowRight'||e.key==='d')keys.right=true;if(e.code==='Space')fire()});addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.left=false;if(e.key==='ArrowRight'||e.key==='d')keys.right=false});for(const [id,k] of [['left','left'],['right','right']]){let b=document.getElementById(id);b.onpointerdown=()=>keys[k]=true;b.onpointerup=b.onpointercancel=()=>keys[k]=false}document.getElementById('fire').onpointerdown=fire;document.getElementById('play').onclick=start;document.getElementById('again').onclick=start;init();'''
(root/'shooter').mkdir(exist_ok=True);(root/'shooter/index.html').write_text(wrap('Cyber Void 3D',shooter_body,shooter_js))

racing_body='''<div id="hud"><div class="pill">🏎️ DATA DRIFT · <span id="score">0</span></div><div class="pill">SPEED <span id="speed">0</span> · ❤️ <span id="hp">100</span></div></div><div id="start" class="screen"><div class="panel"><h1>DATA DRIFT</h1><p>Race through a neon megacity, avoid traffic and build the highest score.</p><button class="btn" id="play">START RACE</button></div></div><div id="over" class="screen hidden"><div class="panel"><h1>RACE OVER</h1><p>Distance score: <b id="final">0</b></p><button class="btn" id="again">RACE AGAIN</button><button class="btn alt" onclick="history.back()">BACK</button></div></div><div class="controls"><button class="control" id="left">◀</button><button class="control wide" id="boost">BOOST</button><button class="control" id="right">▶</button></div>'''
racing_js='''const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();let scene,camera,renderer,car,traffic=[],score=0,hp=100,speed=0,running=false,sessionId=null,last=performance.now();const keys={left:false,right:false,boost:false};
function init(){scene=new THREE.Scene();scene.fog=new THREE.Fog(0x070b18,20,150);camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,300);camera.position.set(0,5,10);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0x9bdcff,0x101020,2));let sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(8,15,10);scene.add(sun);let road=new THREE.Mesh(new THREE.PlaneGeometry(18,500),new THREE.MeshStandardMaterial({color:0x151a28,roughness:.9}));road.rotation.x=-Math.PI/2;road.position.z=-180;scene.add(road);let side=new THREE.MeshStandardMaterial({color:0x0b3442,emissive:0x062a38});for(let x of [-12,12]){let s=new THREE.Mesh(new THREE.BoxGeometry(6,1,500),side);s.position.set(x,-.55,-180);scene.add(s)}for(let z=0;z>-450;z-=9){let m=new THREE.Mesh(new THREE.BoxGeometry(.16,.03,5),new THREE.MeshBasicMaterial({color:0xf5f2c8}));m.position.set(0,.02,z);scene.add(m)}for(let i=0;i<55;i++){for(let x of [-19,-15,15,19]){let h=3+Math.random()*16;let b=new THREE.Mesh(new THREE.BoxGeometry(4,h,7),new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(.55+Math.random()*.18,.4,.12+Math.random()*.12)}));b.position.set(x,h/2,-i*9-Math.random()*8);scene.add(b)}}car=makeCar();scene.add(car);addEventListener('resize',resize);requestAnimationFrame(loop)}
function makeCar(){let g=new THREE.Group();let body=new THREE.Mesh(new THREE.BoxGeometry(2.2,.55,4),new THREE.MeshStandardMaterial({color:0x21bfff,metalness:.8,roughness:.18}));body.position.y=.55;g.add(body);let cabin=new THREE.Mesh(new THREE.BoxGeometry(1.5,.55,1.7),new THREE.MeshStandardMaterial({color:0x0a1730,metalness:.3,roughness:.1}));cabin.position.set(0,1,0);g.add(cabin);for(let x of [-1,1])for(let z of [-1.25,1.25]){let w=new THREE.Mesh(new THREE.CylinderGeometry(.42,.42,.25,16),new THREE.MeshStandardMaterial({color:0x090b10}));w.rotation.z=Math.PI/2;w.position.set(x,0.42,z);g.add(w)}let glow=new THREE.PointLight(0x22ccff,3,8);glow.position.y=.5;g.add(glow);return g}
function makeTraffic(){let c=makeCar();c.scale.setScalar(.82);c.traverse(o=>{if(o.material?.color)o.material=o.material.clone()});c.position.set((Math.floor(Math.random()*3)-1)*4.8,0,-80-Math.random()*100);scene.add(c);traffic.push(c)}
async function startSession(){try{let r=await fetch('/api/game/start',{method:'POST',headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||''},body:JSON.stringify({game:'racing'})});let d=await r.json();if(d.status==='success')sessionId=d.session_id}catch(e){console.warn(e)}}
async function finish(){running=false;document.getElementById('final').textContent=Math.floor(score);document.getElementById('over').classList.remove('hidden');if(sessionId)try{await fetch('/api/save-score',{method:'POST',headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||''},body:JSON.stringify({game:'racing',score:Math.floor(score),session_id:sessionId})})}catch(e){}}
function start(){score=0;hp=100;speed=0;traffic.forEach(x=>scene.remove(x));traffic=[];document.getElementById('start').classList.add('hidden');document.getElementById('over').classList.add('hidden');running=true;startSession()}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
function loop(t){let dt=Math.min(.04,(t-last)/1000);last=t;if(running){let steer=(keys.left?-1:0)+(keys.right?1:0);car.position.x+=steer*9*dt;car.position.x=Math.max(-6.5,Math.min(6.5,car.position.x));car.rotation.z=-steer*.12;let target=keys.boost?58:42;speed+=(target-speed)*dt*2;score+=speed*dt*.8;traffic.forEach((v,i)=>{v.position.z+=speed*dt;if(v.position.z>14){v.position.z=-120-Math.random()*80;v.position.x=(Math.floor(Math.random()*3)-1)*4.8;score+=20}if(v.position.distanceTo(car.position)<2.2){hp-=30;v.position.z=-100;document.getElementById('hp').textContent=Math.max(0,hp)}});if(hp<=0)finish();document.getElementById('score').textContent=Math.floor(score);document.getElementById('speed').textContent=Math.floor(speed*4)}camera.position.x+=(car.position.x*.35-camera.position.x)*dt*4;camera.lookAt(car.position.x*.2,1,-20)}renderer.render(scene,camera);requestAnimationFrame(loop)}
addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.left=true;if(e.key==='ArrowRight'||e.key==='d')keys.right=true;if(e.code==='Space')keys.boost=true});addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.left=false;if(e.key==='ArrowRight'||e.key==='d')keys.right=false;if(e.code==='Space')keys.boost=false});for(const [id,k] of [['left','left'],['right','right'],['boost','boost']]){let b=document.getElementById(id);b.onpointerdown=()=>keys[k]=true;b.onpointerup=b.onpointercancel=()=>keys[k]=false}document.getElementById('play').onclick=()=>{for(let i=0;i<5;i++)makeTraffic();start()};document.getElementById('again').onclick=()=>{for(let i=0;i<5;i++)makeTraffic();start()};init();'''
(root/'racing').mkdir(exist_ok=True);(root/'racing/index.html').write_text(wrap('Data Drift 3D',racing_body,racing_js))

fight_body='''<div id="hud"><div class="pill">🥊 CORE BREAKER · <span id="score">0</span></div><div class="pill"><div class="bar"><div id="hp" class="fill"></div></div></div></div><div id="start" class="screen"><div class="panel"><h1>CORE BREAKER</h1><p>Step into a 3D arena. Move, strike and defeat the rival fighter before your health reaches zero.</p><button class="btn" id="play">ENTER ARENA</button></div></div><div id="over" class="screen hidden"><div class="panel"><h1 id="result">K.O.</h1><p>Score: <b id="final">0</b></p><button class="btn" id="again">FIGHT AGAIN</button><button class="btn alt" onclick="history.back()">BACK</button></div></div><div class="controls"><button class="control" id="left">◀</button><button class="control" id="punch">👊</button><button class="control" id="kick">🦵</button><button class="control" id="right">▶</button></div>'''
fight_js='''const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();let scene,camera,renderer,player,enemy,score=0,php=100,ehp=100,running=false,sessionId=null,last=performance.now(),attack=0,enemyTimer=0;const keys={left:false,right:false};
function init(){scene=new THREE.Scene();scene.fog=new THREE.Fog(0x090812,.025);camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,200);camera.position.set(0,6,16);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xaabfff,0x151018,2));let l=new THREE.DirectionalLight(0xffffff,2.5);l.position.set(5,12,8);scene.add(l);let floor=new THREE.Mesh(new THREE.CylinderGeometry(9,9,.5,48),new THREE.MeshStandardMaterial({color:0x24213a,metalness:.25,roughness:.7}));floor.position.y=-.3;scene.add(floor);let ring=new THREE.Mesh(new THREE.TorusGeometry(8.4,.12,12,64),new THREE.MeshBasicMaterial({color:0x42dcff}));ring.position.y=.05;scene.add(ring);player=makeFighter(0x21cfff);enemy=makeFighter(0xff3b67);player.position.x=-3;enemy.position.x=3;enemy.rotation.y=Math.PI;scene.add(player,enemy);addEventListener('resize',resize);requestAnimationFrame(loop)}
function makeFighter(color){let g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color,metalness:.35,roughness:.35}),dark=new THREE.MeshStandardMaterial({color:0x151a2c,metalness:.4});let torso=new THREE.Mesh(new THREE.CapsuleGeometry(.65,1.2,6,12),mat);torso.position.y=1.8;g.add(torso);let head=new THREE.Mesh(new THREE.SphereGeometry(.5,16,12),mat);head.position.y=3.15;g.add(head);for(let s of [-1,1]){let arm=new THREE.Mesh(new THREE.CapsuleGeometry(.22,.85,5,10),mat);arm.position.set(s*.9,2,.0);arm.rotation.z=s*.35;g.add(arm);let fist=new THREE.Mesh(new THREE.SphereGeometry(.27,12,8),dark);fist.position.set(s*1.15,1.55,.0);g.add(fist);let leg=new THREE.Mesh(new THREE.CapsuleGeometry(.27,1.05,5,10),dark);leg.position.set(s*.38,.55,0);g.add(leg)}return g}
async function startSession(){try{let r=await fetch('/api/game/start',{method:'POST',headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||''},body:JSON.stringify({game:'fighting'})});let d=await r.json();if(d.status==='success')sessionId=d.session_id}catch(e){console.warn(e)}}
async function finish(win){running=false;document.getElementById('result').textContent=win?'VICTORY':'K.O.';document.getElementById('final').textContent=score;document.getElementById('over').classList.remove('hidden');if(sessionId)try{await fetch('/api/save-score',{method:'POST',headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||''},body:JSON.stringify({game:'fighting',score,session_id:sessionId})})}catch(e){}}
function start(){php=100;ehp=100;score=0;attack=0;enemyTimer=0;player.position.x=-3;enemy.position.x=3;document.getElementById('hp').style.width='100%';document.getElementById('start').classList.add('hidden');document.getElementById('over').classList.add('hidden');running=true;startSession()}
function hit(kind){if(!running||attack>0)return;attack=.35;player.rotation.y=(kind==='punch'?.25:-.25);let dist=Math.abs(player.position.x-enemy.position.x);if(dist<3){ehp-=kind==='punch'?16:24;score+=kind==='punch'?40:60;enemy.position.x+=player.position.x<enemy.position.x?.35:-.35;if(ehp<=0)finish(true)}}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
function loop(t){let dt=Math.min(.04,(t-last)/1000);last=t;if(running){let dir=(keys.left?-1:0)+(keys.right?1:0);player.position.x+=dir*4*dt;player.position.x=Math.max(-6.2,Math.min(6.2,player.position.x));player.rotation.y=dir*.12;attack=Math.max(0,attack-dt);if(attack===0)player.rotation.y=0;enemyTimer-=dt;if(enemyTimer<0){enemyTimer=1+Math.random();let d=Math.abs(enemy.position.x-player.position.x);if(d<3){php-=Math.random()<.55?9:14;document.getElementById('hp').style.width=Math.max(0,php)+'%';if(php<=0)finish(false)}else enemy.position.x+=Math.sign(player.position.x-enemy.position.x)*Math.min(.9,d)}camera.position.x+=(player.position.x*.25-camera.position.x)*dt*3;camera.lookAt((player.position.x+enemy.position.x)/2,1.8,0)}renderer.render(scene,camera);requestAnimationFrame(loop)}
addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.left=true;if(e.key==='ArrowRight'||e.key==='d')keys.right=true;if(e.key==='j')hit('punch');if(e.key==='k')hit('kick')});addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='a')keys.left=false;if(e.key==='ArrowRight'||e.key==='d')keys.right=false});for(const [id,k] of [['left','left'],['right','right']]){let b=document.getElementById(id);b.onpointerdown=()=>keys[k]=true;b.onpointerup=b.onpointercancel=()=>keys[k]=false}document.getElementById('punch').onpointerdown=()=>hit('punch');document.getElementById('kick').onpointerdown=()=>hit('kick');document.getElementById('play').onclick=start;document.getElementById('again').onclick=start;init();'''
(root/'fighting').mkdir(exist_ok=True);(root/'fighting/index.html').write_text(wrap('Core Breaker 3D',fight_body,fight_js))
